import React, { Component } from "react";
import BreadCrumbNCover from "./BreadCrumbNCover";
const pageName = "Research";

const referencePageURL =
  "https://drive.google.com/file/d/1OZ-QXh2LtxlVmx2bpNRYXC2jfQdmlB7y/view?usp=sharing";
export default class Portfolio extends Component {
  render() {
    return (
      <div>
        <BreadCrumbNCover pageName={pageName} />
        <div className="container">
          <div className="row">
            <div className="col-12">
              {/* <!-- Section Heading --> */}
              <div className="section-heading text-center">
                <h2>Fire retardant trees in a nutshell</h2>
              </div>
              <div>
                <p>
                  Bushfires are a common occurrence in summer for most
                  Australians, and protecting your family, pets and property
                  does not have to be difficult if you plan ahead.
                </p>

                <p>Fire-retardant trees can protect from fire in 3 ways:</p>

                <ul>
                  <li>
                    <strong>1. By acting as a shield:</strong>
                    <p>
                      Fire retardant trees act as a shield against the immense
                      radiant heat generated by an approaching fire, so that the
                      houseis protected from the intense temperatures that can
                      shatter windows and melt materials.
                    </p>
                  </li>
                  <li>
                    <strong>2. Acting to trap the burning:</strong>
                    <p>
                      A large canopied tree, or a strategically placed hedge,
                      acts to trap the burning material carried in the intense
                      fire winds. This reduces the amount of flaming matter that
                      can reach and ignite the building itself.
                    </p>
                  </li>
                  <li>
                    <strong>3. Storing moisture in the leaves:</strong>
                    <p>
                      Stored moisture in the leaves acts as all water does; it
                      suppresses the fire's energy. Many times, even a single
                      tree has saved a house or shed. That's why fire-retardant
                      trees are living firebreaks.
                    </p>
                  </li>
                </ul>
                <img id="ref-image" src="img/B9.jpg" alt="" />
                <p>
                  <strong>REMEMBER</strong> - fire retardant plants are only one
                  aspect of preparing your property to withstand fire. Seek
                  information on house design, water use and personal fire plans
                  from your local authorities.
                </p>
                <p>
                  Having a garden containing fire retardant plants will not
                  necessarily stop a fire from damaging your house but may help
                  slow the fire and reduce radiant heat.
                </p>
                <p>
                  To know more details about fire retardant trees and our
                  categories' descriptions, please go to{" "}
                  <a id="ref-link" href={referencePageURL} target="_blank">THIS PAGE.</a>
                </p>
                <br/>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
